name: builder
on: [push]
jobs:
  builder:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@v3

      - name: setup qume
        uses: docker/setup-qemu-action@v2

      - name: setup buildx
        uses: docker/setup-buildx-action@v2

      - name: login registry
        uses: docker/login-action@v2
        with:
          registry: ${{secrets.DOCKER_REGISTRY}}
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASS}}

      - name: build image
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: registry.cn-shenzhen.aliyuncs.com/beanjs/beanjs-offical:latest

      - name: shell
        run: ls && env && docker images
